### ISSUE TITLE
Unable to build

### ISSUE THREAD

**Issue by xmattstrongx** [UltimateSoftware/ultipkg#1]
I have been trying to build/test this project with `rake build`, `go build` and 'go test'.
Cant seem to get past this error without modifying the imports significantly. Would like to compare notes and see if this is environmental or not.

Also I am on go1.5 with the environment variable GO15VENDOREXPERIMENT=1 

`matthewst@matthewst  ~/go/src/forks/ultipkg  go test`

```# forks/ultipkg
./main.go:36: cannot use Logger (type *"forks/ultipkg/vendor/github.com/Sirupsen/logrus".Logger) as type *"pkg.ulti.io/ultimate/ultipkg-dist/vendor/github.com/Sirupsen/logrus".Logger in assignment
FAIL	forks/ultipkg [build failed]```



thoughts?

**Comment by xmattstrongx** [comment]
PR in for this in case you want to use the resolution I was able to find 
#2

**Comment by ryanfaerman** [comment]
@xmattstrongx You should be able to build now.
